name: video_player_for_web_integration_tests
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    path: ../../video_player_platform_interface
  video_player_web:
    path: ../
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
