name: video_player_android_fork
description: Android implementation of the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.4.10
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface_fork:
    git: 
      url: https://github.com/Ahlisen/packages
      path: packages/video_player/video_player_platform_interface
      ref: 8c0f3c1307582ec0adcdb781e2bab1756d9db28a

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.5

topics:
  - video
  - video-player
