name: video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
publish_to: none
version: 2.7.14

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    git:
      url: https://github.com/Ahlisen/packages
      path: packages/video_player/video_player_platform_interface
      ref: 551ee97c0899b55dcca624271337fd666cc379c9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.4.2

topics:
  - video
  - video-player
